import { initializeApp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js";
import { getAuth, signInAnonymously, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js";
import { getFirestore, collection, doc, getDoc, getDocs, limit, onSnapshot, query, runTransaction, serverTimestamp, setDoc, updateDoc, writeBatch } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js";

const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const TEACHER_EMAIL = "t2bin@uryeo-h.gne.go.kr";
const firebaseApp = initializeApp(window.FIREBASE_CONFIG);
const auth = getAuth(firebaseApp);
const db = getFirestore(firebaseApp);
const TEAM_COLORS = ["#d8473c", "#2678ac", "#3d9255", "#db9b2f", "#7956a4", "#db6f9f", "#258c85", "#7d5535"];
const TOKENS = ["🐴","🐯","🐰","🐲","🦊","🐻","🐼","🐵","🦁","🐸","🐧","🦄","🐶","🐱","🐨","🐹","🦋","🐢","🦖","🐝","🦅","🐺","🐳","🦌","🐘"];
const state = { teams: [], current: 0, locked: true, lands: Array(81).fill(null), luck: new Set(), bad: new Set(), quizzes: [], wrong: [], asked: 0, correct: 0, activeSetupTeam: 0, lastRoll: 0, timer: null, turnNonce: 1, revision: 0 };
const online = { roomId: null, code: null, isHost: false, unsub: null, applying: false };
const ITEMS = { shield:["방어패","상대의 땅 공격을 한 번 막습니다."], retry:["재도전권","오답일 때 한 번 더 답합니다."], hint:["쌍답권","정답을 두 개까지 고를 수 있습니다."], dice:["주사위 조작","굴린 뒤 숫자를 6으로 바꿉니다."], freeze:["멈춰라!","다른 팀 한 곳을 한 턴 쉬게 합니다."] };

function showScreen(id){ $$(".screen").forEach(x=>x.classList.toggle("active",x.id===id)); }
function sanitizeHtml(html){ const doc=new DOMParser().parseFromString(String(html||""),"text/html"); const ok=new Set(["DIV","P","SPAN","BR","B","STRONG","EM","U","TABLE","TBODY","TR","TD","TH","UL","OL","LI","IMG"]); [...doc.body.querySelectorAll("*")].forEach(el=>{ if(!ok.has(el.tagName)){el.replaceWith(...el.childNodes);return;} [...el.attributes].forEach(a=>{if(a.name.startsWith("on")||!["class","colspan","rowspan","src","alt"].includes(a.name))el.removeAttribute(a.name);}); if(el.tagName==="IMG"&&!/^data:image\//.test(el.getAttribute("src")||""))el.remove(); }); return doc.body.innerHTML; }

function makeRoomCode(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join("")}
function publicSnapshot(){return{teams:state.teams.map(t=>({...t,items:[...t.items]})),current:state.current,locked:state.locked,lands:[...state.lands],luck:[...state.luck],bad:[...state.bad],asked:state.asked,correct:state.correct,lastRoll:state.lastRoll,turnNonce:state.turnNonce,revision:state.revision}}
function applySnapshot(s){if(!s||s.revision<=state.revision)return;online.applying=true;state.teams=s.teams||[];state.current=s.current||0;state.locked=!!s.locked;state.lands=s.lands||Array(81).fill(null);state.luck=new Set(s.luck||[]);state.bad=new Set(s.bad||[]);state.asked=s.asked||0;state.correct=s.correct||0;state.lastRoll=s.lastRoll||0;state.turnNonce=s.turnNonce||1;state.revision=s.revision||0;online.applying=false;if(state.teams.length){renderGame();showScreen("game-screen")}updateOnlineBadges()}
function updateOnlineBadges(){if($("#room-label"))$("#room-label").textContent=online.code?`입장 코드 ${online.code}`:"교실 게임";if($("#room-code-value"))$("#room-code-value").textContent=online.code?`입장 코드 ${online.code}`:"새 게임을 만들면 입장 코드 표시";if($("#active-games"))$("#active-games").textContent=online.roomId?"1":"0";if($("#joined-team-count"))$("#joined-team-count").textContent=state.teams.filter(t=>t.ownerUid).length}
function subscribeRoom(){online.unsub?.();if(!online.roomId)return;online.unsub=onSnapshot(doc(db,"rooms",online.roomId),snap=>{if(snap.exists())applySnapshot(snap.data().snapshot)})}
async function createOnlineRoom(){online.isHost=true;online.roomId=crypto.randomUUID();for(let tries=0;tries<8;tries++){online.code=makeRoomCode();if(!(await getDoc(doc(db,"roomCodes",online.code))).exists())break}state.revision=1;const snapshot=publicSnapshot();const batch=writeBatch(db);batch.set(doc(db,"rooms",online.roomId),{teacherId:auth.currentUser.uid,code:online.code,status:"playing",snapshot,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});batch.set(doc(db,"roomCodes",online.code),{roomId:online.roomId,active:true,createdAt:serverTimestamp()});batch.set(doc(db,"rooms",online.roomId,"players",auth.currentUser.uid),{role:"teacher",teamIndex:-1,joinedAt:serverTimestamp()});await batch.commit();subscribeRoom();updateOnlineBadges();await loadQuizBank()}
async function joinOnlineRoom(){const errorBox=$("#join-error"),code=$("#join-code").value.trim().toUpperCase(),name=$("#join-team-name").value.trim();if(code.length!==6){errorBox.textContent="6자리 입장 코드를 입력하세요.";return}errorBox.textContent="입장 중입니다…";try{if(!auth.currentUser)await signInAnonymously(auth);const codeSnap=await getDoc(doc(db,"roomCodes",code));if(!codeSnap.exists()||!codeSnap.data().active)throw new Error("사용할 수 없는 입장 코드입니다.");const roomId=codeSnap.data().roomId,roomRef=doc(db,"rooms",roomId),playerRef=doc(db,"rooms",roomId,"players",auth.currentUser.uid);let joinedIndex=-1;await runTransaction(db,async tx=>{const roomSnap=await tx.get(roomRef);if(!roomSnap.exists())throw new Error("게임방을 찾을 수 없습니다.");const data=roomSnap.data(),snapshot=data.snapshot,teams=snapshot.teams.map(t=>({...t}));joinedIndex=teams.findIndex(t=>t.ownerUid===auth.currentUser.uid);if(joinedIndex<0)joinedIndex=teams.findIndex(t=>!t.ownerUid);if(joinedIndex<0)throw new Error("모든 팀 자리가 찼습니다.");teams[joinedIndex].ownerUid=auth.currentUser.uid;if(name)teams[joinedIndex].name=name;const next={...snapshot,teams,revision:(snapshot.revision||0)+1};tx.set(playerRef,{role:"student",teamIndex:joinedIndex,teamName:teams[joinedIndex].name,joinedAt:serverTimestamp()});tx.update(roomRef,{snapshot:next,updatedAt:serverTimestamp()})});online.roomId=roomId;online.code=code;online.isHost=false;state.revision=0;subscribeRoom();await loadQuizBank();$("#join-dialog").close();updateOnlineBadges()}catch(error){errorBox.textContent=error.message}}

function cat(p0,p1,p2,p3,t){const t2=t*t,t3=t2*t;return [.5*(2*p1[0]+(-p0[0]+p2[0])*t+(2*p0[0]-5*p1[0]+4*p2[0]-p3[0])*t2+(-p0[0]+3*p1[0]-3*p2[0]+p3[0])*t3),.5*(2*p1[1]+(-p0[1]+p2[1])*t+(2*p0[1]-5*p1[1]+4*p2[1]-p3[1])*t2+(-p0[1]+3*p1[1]-3*p2[1]+p3[1])*t3)];}
function boardPositions(){const cp=[[1450,720],[1170,735],[820,735],[460,730],[185,665],[160,500],[330,435],[650,520],[920,550],[1210,500],[1435,430],[1430,245],[1240,170],[980,170],[800,175]],dense=[];for(let i=0;i<cp.length-1;i++)for(let j=0;j<100;j++)dense.push(cat(cp[Math.max(0,i-1)],cp[i],cp[i+1],cp[Math.min(cp.length-1,i+2)],j/100));dense.push(cp.at(-1));const len=[0];for(let i=1;i<dense.length;i++)len.push(len.at(-1)+Math.hypot(dense[i][0]-dense[i-1][0],dense[i][1]-dense[i-1][1]));const out=[];let c=0;for(let i=0;i<80;i++){const target=len.at(-1)*i/79;while(len[c+1]<target)c++;const r=(target-len[c])/(len[c+1]-len[c]),a=dense[c],b=dense[c+1];out.push({x:(a[0]+(b[0]-a[0])*r)/16,y:(a[1]+(b[1]-a[1])*r)/9});}return out;}
const POS=boardPositions();

function setupTeams(count=4){const old=state.teams;state.teams=Array.from({length:count},(_,i)=>old[i]||{id:crypto.randomUUID(),name:`${i+1}팀`,token:TOKENS[i],color:TEAM_COLORS[i],position:1,items:[],skip:0,correct:0,wrong:0,ownerUid:null});state.activeSetupTeam=Math.min(state.activeSetupTeam,count-1);renderSetup();}
function renderSetup(){ $("#team-count").innerHTML=[4,5,6,7,8].map(n=>`<button class="${state.teams.length===n?'active':''}" data-count="${n}">${n}</button>`).join(""); $("#team-fields").innerHTML=state.teams.map((t,i)=>`<div class="team-field ${i===state.activeSetupTeam?'active':''}" data-team="${i}"><button>${t.token}</button><input value="${t.name}" maxlength="12" aria-label="${i+1}팀 이름"></div>`).join(""); $("#active-team-label").textContent=`${state.teams[state.activeSetupTeam].name}의 말 선택`; $("#token-picker").innerHTML=TOKENS.map(x=>`<button class="token-choice ${state.teams[state.activeSetupTeam].token===x?'selected':''}" data-token="${x}">${x}</button>`).join("");}
$("#team-count").onclick=e=>{const n=+e.target.dataset.count;if(n)setupTeams(n)};$("#team-fields").onclick=e=>{const row=e.target.closest(".team-field");if(row){state.activeSetupTeam=+row.dataset.team;renderSetup()}};$("#team-fields").oninput=e=>{const row=e.target.closest(".team-field");if(row&&e.target.tagName==="INPUT"){state.teams[+row.dataset.team].name=e.target.value||`${+row.dataset.team+1}팀`;$("#active-team-label").textContent=`${state.teams[state.activeSetupTeam].name}의 말 선택`}};$("#token-picker").onclick=e=>{if(e.target.dataset.token){state.teams[state.activeSetupTeam].token=e.target.dataset.token;renderSetup()}};

function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function resetGame(){state.current=0;state.locked=false;state.lands=Array(81).fill(null);state.wrong=[];state.asked=state.correct=0;state.turnNonce=1;state.revision=0;state.teams.forEach((t,i)=>Object.assign(t,{position:1,items:[],skip:0,correct:0,wrong:0,color:TEAM_COLORS[i],ownerUid:t.ownerUid||null}));const spots=shuffle(Array.from({length:72},(_,i)=>i+5));state.luck=new Set(spots.slice(0,3));state.bad=new Set(spots.slice(3,6));renderGame();addLog("80칸 역사 탐험을 시작합니다!")}
function renderGame(){const team=state.teams[state.current];if(!team)return;$("#turn-banner").innerHTML=`<span style="color:${team.color}">${team.token} ${team.name}</span>의 차례`;$("#dice-owner").textContent=`${team.name}의 주사위`;$("#team-list").innerHTML=state.teams.map((t,i)=>`<div class="team-card ${i===state.current?'current':''}"><span class="pawn">${t.token}</span><div><b>${t.name}</b><small>${t.position}칸 · 땅 ${state.lands.filter(x=>x===i).length}개${t.ownerUid?' · 접속':' · 대기'}</small></div>${t.skip?'<span class="skip">한 턴 쉼</span>':''}</div>`).join("");renderTokens();renderLands();renderInventory();const myTurn=!online.roomId||online.isHost||team.ownerUid===auth.currentUser?.uid;$("#roll-button").disabled=state.locked||!myTurn;updateOnlineBadges()}
function renderTokens(){const layers=[$("#token-layer"),$("#tv-token-layer")].filter(Boolean);layers.forEach(layer=>layer.innerHTML="");state.teams.forEach((t,i)=>layers.forEach(layer=>{const p=POS[t.position-1],el=document.createElement("div");el.className="player-token";el.textContent=t.token;el.title=`${t.name} ${t.position}칸`;el.style.cssText=`--team-color:${t.color};left:${p.x}%;top:${p.y}%;margin-left:${(i%4-1.5)*7}px;margin-top:${Math.floor(i/4)*7}px`;layer.append(el)}));if($("#tv-status"))$("#tv-status").textContent=`${state.teams[state.current]?.name||"게임"} 차례 · 최근 주사위 ${state.lastRoll||"-"}`;}
function renderLands(){const layer=$("#land-layer");layer.innerHTML="";state.lands.forEach((owner,n)=>{if(owner!==null&&n>1){const p=POS[n-1],el=document.createElement("i");el.className="land-mark";el.style.cssText=`--team-color:${state.teams[owner].color};left:${p.x}%;top:${p.y}%`;layer.append(el)}})}
function renderInventory(){const t=state.teams[state.current],box=$("#inventory");box.innerHTML=t.items.length?`<div class="inventory-items">${t.items.map(k=>`<span class="item-chip">${ITEMS[k][0]}</span>`).join("")}</div>`:`<p class="empty">아직 획득한 아이템이 없습니다.</p>`}
function addLog(text){const li=document.createElement("li");li.textContent=text;$("#game-log").prepend(li);while($("#game-log").children.length>12)$("#game-log").lastChild.remove()}
function toast(text){const el=$("#board-toast");el.textContent=text;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1200)}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function moveTeam(team,target){while(team.position!==target){team.position+=Math.sign(target-team.position);renderTokens();document.querySelectorAll(".player-token")[state.teams.indexOf(team)]?.classList.add("moving");await wait(320)}renderGame();}

let pressStart=0,chargeFrame=0,autoRoll=0;function beginCharge(e){if(state.locked)return;e.preventDefault();pressStart=performance.now();state.locked=true;$("#roll-button").classList.add("charging");const tick=()=>{const p=Math.min(1,(performance.now()-pressStart)/2000);$("#charge-fill").style.width=`${p*100}%`;if(p<1)chargeFrame=requestAnimationFrame(tick);else rollDice()};chargeFrame=requestAnimationFrame(tick);autoRoll=setTimeout(()=>rollDice(),2050)}function releaseCharge(e){if(!pressStart)return;e.preventDefault();rollDice()}
$("#roll-button").addEventListener("pointerdown",beginCharge);window.addEventListener("pointerup",releaseCharge);
async function rollDice(){if(!pressStart)return;pressStart=0;cancelAnimationFrame(chargeFrame);clearTimeout(autoRoll);$("#roll-button").classList.remove("charging");const dice=$("#dice");dice.classList.add("rolling");for(let i=0;i<12;i++){dice.textContent=1+Math.floor(Math.random()*6);await wait(70+i*6)}let value=1+Math.floor(Math.random()*6);dice.textContent=value;dice.classList.remove("rolling");state.lastRoll=value;$("#charge-fill").style.width="0";const team=state.teams[state.current];addLog(`${team.name}: 주사위 ${value}`);if(team.items.includes("dice")){const use=await askItem("dice");if(use){team.items.splice(team.items.indexOf("dice"),1);value=6;state.lastRoll=6;dice.textContent=6;toast("주사위가 6으로 변경!")}}const from=team.position,target=Math.min(80,from+value);await moveTeam(team,target);if(target===80){finishGame(team);return}await resolveLanding(team,from)}
function askItem(key){return new Promise(resolve=>{const d=$("#item-dialog");$("#item-title").textContent=ITEMS[key][0];$("#item-message").textContent=ITEMS[key][1]+" 지금 사용할까요?";$("#item-use").onclick=()=>{d.close();resolve(true)};$("#item-skip").onclick=()=>{d.close();resolve(false)};d.showModal()})}

async function resolveLanding(team,from){if(state.luck.has(team.position)){await luckyEvent(team);endTurn();return}if(state.bad.has(team.position)){await badEvent(team);endTurn();return}askQuiz(team,from)}
function randomQuiz(){return state.quizzes[Math.floor(Math.random()*state.quizzes.length)]||null}
function normalizeQuiz(q){if(Array.isArray(q))return{category:q[0],difficulty:q[1],html:q[2],choices:q[3],answer:q[4],time:null};return q}
async function verifyQuizAnswer(q,answer,attemptNo){if(Number.isInteger(q.answer))return q.answer===answer;if(!online.roomId)throw new Error("온라인 게임방 연결이 필요합니다.");const uid=auth.currentUser.uid,attemptId=`${state.turnNonce}_${uid}_${attemptNo}`,attemptRef=doc(db,"rooms",online.roomId,"attempts",attemptId),correctRef=doc(db,"rooms",online.roomId,"correct",attemptId);await setDoc(attemptRef,{userId:uid,questionId:q.id,selectedAnswer:answer,createdAt:serverTimestamp()});try{await setDoc(correctRef,{userId:uid,questionId:q.id,createdAt:serverTimestamp()});return true}catch(error){if(error.code==="permission-denied")return false;throw error}}
async function askQuiz(team,from){const q=randomQuiz(),d=$("#quiz-dialog");if(!q){alert("등록된 퀴즈가 없습니다. 교사 대시보드에서 XLSX를 업로드하세요.");await moveTeam(team,from);endTurn();return}state.asked++;$("#quiz-category").textContent=`${q.category} · ${q.difficulty}`;$("#quiz-question").innerHTML=sanitizeHtml(q.html);$("#quiz-feedback").textContent="";let budget=1,answered=[];if(team.items.includes("hint")&&await askItem("hint")){team.items.splice(team.items.indexOf("hint"),1);budget=2}$("#quiz-choices").innerHTML=q.choices.map((c,i)=>`<button type="button" class="quiz-choice" data-answer="${i+1}"><b>${i+1}.</b> ${c}</button>`).join("");const finish=async(correct,correctAnswer)=>{clearInterval(state.timer);$$('.quiz-choice').forEach((b,i)=>{b.disabled=true;if(i+1===(q.answer||correctAnswer))b.classList.add("correct")});if(correct){state.correct++;team.correct++;$("#quiz-feedback").textContent="정답입니다! 이 땅을 차지했습니다.";await wait(950);d.close();await onCorrect(team,from)}else{team.wrong++;state.wrong.push({...q,team:team.name});$("#quiz-feedback").textContent="아쉽습니다. 원래 칸으로 돌아갑니다.";await wait(950);d.close();await moveTeam(team,from);endTurn()}};$("#quiz-choices").onclick=async e=>{const b=e.target.closest("button");if(!b||b.disabled)return;const a=+b.dataset.answer;if(answered.includes(a))return;answered.push(a);b.disabled=true;try{const correct=await verifyQuizAnswer(q,a,answered.length);if(correct){finish(true,a);return}b.classList.add("wrong");budget--;if(budget<=0){if(team.items.includes("retry")&&await askItem("retry")){team.items.splice(team.items.indexOf("retry"),1);budget=1;$("#quiz-feedback").textContent="재도전 기회!"}else finish(false)}}catch(error){$("#quiz-feedback").textContent=`채점 연결 오류: ${error.message}`;b.disabled=false}};if(q.time){let left=q.time;$("#quiz-timer").textContent=`⏱ ${left}초`;state.timer=setInterval(()=>{$("#quiz-timer").textContent=`⏱ ${--left}초`;if(left<=0)finish(false)},1000)}else $("#quiz-timer").textContent="";d.showModal()}
async function onCorrect(team,from){const idx=state.teams.indexOf(team),owner=state.lands[team.position];if(owner!==null&&owner!==idx){const defender=state.teams[owner];if(defender.items.includes("shield")){defender.items.splice(defender.items.indexOf("shield"),1);toast(`${defender.name}이 방어패 사용!`);addLog(`${defender.name}의 땅 방어 성공`)}else{defender.position=from;state.lands[team.position]=idx;toast(`${defender.name}과 자리 교환!`);addLog(`${team.name}이 ${defender.name}의 땅을 차지`);renderTokens()}}else{state.lands[team.position]=idx;toast("정답! 땅 차지 완료")}endTurn()}
function showEvent(icon,title,msg){return new Promise(r=>{const d=$("#event-dialog");$("#event-icon").textContent=icon;$("#event-title").textContent=title;$("#event-message").textContent=msg;$("#event-confirm").onclick=()=>{d.close();r()};d.showModal()})}
async function luckyEvent(team){const outcomes=["shield","retry","hint","dice","freeze"],item=outcomes[Math.floor(Math.random()*outcomes.length)];team.items.push(item);await showEvent("🍀","비밀 행운 칸!",`${ITEMS[item][0]} 획득 — ${ITEMS[item][1]}`);addLog(`${team.name}: ${ITEMS[item][0]} 획득`)}
async function badEvent(team){team.skip++;$("#board-shell").classList.add("shake");await wait(500);$("#board-shell").classList.remove("shake");await showEvent("🌩️","비밀 불운 칸!",`${team.name}은 다음 차례를 한 번 쉽니다.`);addLog(`${team.name}: 한 턴 쉼`)}
function endTurn(){state.locked=true;syncState();setTimeout(()=>{let tries=0;do{state.current=(state.current+1)%state.teams.length;if(state.teams[state.current].skip){state.teams[state.current].skip--;addLog(`${state.teams[state.current].name}: 쉬어가는 차례`)}else break}while(++tries<state.teams.length);state.turnNonce++;state.locked=false;renderGame();syncState()},650)}
function finishGame(team){state.locked=true;$("#winner-title").textContent=`${team.token} ${team.name} 승리!`;$("#winner-dialog").showModal();syncState()}

function renderReport(){const accuracy=state.asked?Math.round(state.correct/state.asked*100):0;$("#report-summary").innerHTML=`<div class="summary-grid"><div class="summary-box"><b>${state.asked}</b><small>푼 문제</small></div><div class="summary-box"><b>${accuracy}%</b><small>정답률</small></div><div class="summary-box"><b>${state.wrong.length}</b><small>오답</small></div></div>`;$("#wrong-note").innerHTML=state.wrong.length?`<h3>오답 노트</h3>${state.wrong.map(q=>`<div class="wrong-card"><b>${q.team} · ${q.category}</b><div>${sanitizeHtml(q.html)}</div><small>정답: ${q.answer}번 ${q.choices[q.answer-1]}</small></div>`).join("")}`:`<p class="empty">아직 기록된 오답이 없습니다.</p>`;$("#report-dialog").showModal()}

async function teacherLogin(){
  if(auth.currentUser?.email?.toLowerCase()===TEACHER_EMAIL){await loadQuizBank();showScreen("teacher-screen");return}
  const d=$("#password-dialog");$("#teacher-password").value="";$("#password-error").textContent="";d.showModal();$("#teacher-password").focus();
}
async function submitTeacherAuth(){
  const password=$("#teacher-password").value;
  const errorBox=$("#password-error");
  if(password.length<8){errorBox.textContent="비밀번호는 8자 이상 입력하세요.";return}
  errorBox.textContent="로그인 중입니다…";
  try{
    const credential=await signInWithEmailAndPassword(auth,TEACHER_EMAIL,password);
    if(credential.user.email?.toLowerCase()!==TEACHER_EMAIL){await signOut(auth);throw new Error("허용된 교사 계정이 아닙니다.")}
    $("#password-dialog").close();await loadQuizBank();showScreen("teacher-screen");
  }catch(error){errorBox.textContent=error.code==="auth/invalid-credential"?"이메일 또는 비밀번호가 올바르지 않습니다.":error.message}
}
$("#password-submit").onclick=submitTeacherAuth;
$("#join-submit").onclick=joinOnlineRoom;
$("#student-entry").onclick=()=>{$("#join-code").value="";$("#join-team-name").value="";$("#join-error").textContent="";$("#join-dialog").showModal()};$("#teacher-entry").onclick=teacherLogin;$$('.back-home').forEach(b=>b.onclick=()=>showScreen("home-screen"));$("#start-game").onclick=async()=>{try{resetGame();await createOnlineRoom();showScreen("game-screen")}catch(error){alert(`게임방 생성 실패: ${error.message}`)}};$("#teacher-start").onclick=()=>{online.isHost=true;setupTeams(4);showScreen("setup-screen")};$("#exit-game").onclick=()=>showScreen("home-screen");$("#open-report").onclick=renderReport;$("#winner-report").onclick=()=>{$("#winner-dialog").close();renderReport()};
function openTv(){window.open(`${location.pathname}#tv`,"history-tv","noopener")};$("#tv-button").onclick=openTv;$("#teacher-tv").onclick=openTv;
const channel=new BroadcastChannel("history-exploration");async function syncState(){const safe={teams:state.teams.map(({name,token,color,position})=>({name,token,color,position})),current:state.current,lastRoll:state.lastRoll};localStorage.setItem("history-game-state",JSON.stringify(safe));channel.postMessage(safe);if(online.roomId&&!online.applying){state.revision++;try{await updateDoc(doc(db,"rooms",online.roomId),{snapshot:publicSnapshot(),updatedAt:serverTimestamp()})}catch(error){console.error("Firestore sync failed",error)}}}channel.onmessage=e=>{if(location.hash==="#tv")applyTv(e.data)};function applyTv(data){if(!data?.teams)return;state.teams=data.teams;state.current=data.current;state.lastRoll=data.lastRoll;renderTokens()}if(location.hash==="#tv"){showScreen("tv-screen");try{applyTv(JSON.parse(localStorage.getItem("history-game-state")))}catch{}}else showScreen("home-screen");

function parseWorkbook(file){return new Promise((resolve,reject)=>{if(!window.XLSX)return reject(new Error("XLSX 라이브러리를 불러오지 못했습니다."));const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{try{const wb=XLSX.read(reader.result,{type:"array"}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""});const req=["카테고리","난이도(하/중/고)","문제","선택지1","선택지2","선택지3","선택지4","선택지5","정답번호(1~5)"];if(!rows.length||req.some(k=>!(k in rows[0])))throw new Error("필수 열 이름이 양식과 다릅니다.");resolve(rows.map(r=>({category:String(r["카테고리"]),difficulty:String(r["난이도(하/중/고)"]),html:sanitizeHtml(r["문제"]),choices:[1,2,3,4,5].map(i=>String(r[`선택지${i}`])),answer:Number(r["정답번호(1~5)"]),time:Number(r["제한시간(초, 선택)"])||null})).filter(q=>q.answer>=1&&q.answer<=5))}catch(e){reject(e)}};reader.readAsArrayBuffer(file)})}
async function uploadQuizBank(qs){if(auth.currentUser?.email?.toLowerCase()!==TEACHER_EMAIL)throw new Error("교사 로그인 후 업로드할 수 있습니다.");const batch=writeBatch(db);qs.forEach((q,i)=>{const id=`q${String(i+1).padStart(4,"0")}`;batch.set(doc(db,"quizPublic",id),{category:q.category,difficulty:q.difficulty,html:q.html,choices:q.choices,time:q.time||null,active:true,order:i+1,updatedAt:serverTimestamp()});batch.set(doc(db,"quizAnswers",id),{answer:q.answer,updatedAt:serverTimestamp()})});batch.set(doc(db,"metadata","quizBank"),{count:qs.length,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid});await batch.commit()}
async function loadQuizBank(){if(!auth.currentUser)return;const publicDocs=await getDocs(query(collection(db,"quizPublic"),limit(500)));const items=publicDocs.docs.map(d=>({id:d.id,...d.data()})).filter(q=>q.active!==false).sort((a,b)=>(a.order||0)-(b.order||0));if(auth.currentUser.email?.toLowerCase()===TEACHER_EMAIL){const answerDocs=await getDocs(query(collection(db,"quizAnswers"),limit(500))),answers=new Map(answerDocs.docs.map(d=>[d.id,d.data().answer]));items.forEach(q=>q.answer=answers.get(q.id))}state.quizzes=items;$("#question-count").textContent=items.length;return items}
$("#quiz-upload").onchange=async e=>{const out=$("#upload-result");try{out.textContent="업로드 및 정답 분리 저장 중…";const qs=await parseWorkbook(e.target.files[0]);await uploadQuizBank(qs);await loadQuizBank();out.textContent=`✅ ${qs.length}개 문제를 Firestore에 저장했습니다.`}catch(err){out.textContent=`❌ ${err.message}`}};
$("#download-template").onclick=()=>{if(!window.XLSX){alert("다운로드 도구를 불러오지 못했습니다.");return}const headers=[["카테고리","난이도(하/중/고)","문제","선택지1","선택지2","선택지3","선택지4","선택지5","정답번호(1~5)","제한시간(초, 선택)"]],ws=XLSX.utils.aoa_to_sheet(headers),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"문제_양식");XLSX.writeFile(wb,"한국사_퀴즈_빈양식.xlsx")};
setupTeams(4);updateOnlineBadges();
